services:
  backend:
    image: "${DOCKER_USERNAME}/my-backend:latest"
    restart: always
    ports:
      - "8080:8080"
    environment:
      - FIREBASE_CONFIG_PATH=/app/firebase-codeness-key.json
    volumes:
      - /home/ubuntu/codeness/firebase-codeness-key.json:/app/firebase-codeness-key.json
      - /home/ubuntu/codeness/credentials.json:/app/credentials.json