version: '3.8'

services:
  backend:
    image: my-backend
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - FIREBASE_CONFIG_BASE64=${FIREBASE_CONFIG_BASE64}