### 회원가입
POST localhost:8080/signup
Content-Type: application/json

{
  "email" : "1aaaaaaaa@naver.com",
  "password" : "asdf1234!@",
  "name" : "이름",
  "nickname" : "열일하는 개발자",
  "phoneNumber" : "010 - 1234 - 6328",
  "field" : "BACKEND",
  "userRole" : "ADMIN"
}

### 로그인
POST localhost:8080/login
Content-Type: application/json

{
  "email" : "1aaaaaaaa@naver.com",
  "password" : "asdf1234!@"
}

> {%
  client.global.set("token",response.body.token);
  client.log("Token saved: " + client.global.get("token"));
%}

### 멘토 정산 처리 API
PATCH localhost:8080/admin/mentors/1/settlements
Authorization: Bearer {{token}}

### 전체 멘토 리스트 조회 API
GET localhost:8080/admin/mentors
Authorization: Bearer {{token}}

### 멘토 상세 조회 API
GET localhost:8080/admin/mentors/1
Authorization: Bearer {{token}}

### 멘토 신청 리스트 조회 API
GET localhost:8080/admin/mentors/mentor-requests
Authorization: Bearer {{token}}

### 멘토 신청 상세 조회 API
GET localhost:8080/admin/mentors/mentor-requests/1
Authorization: Bearer {{token}}

### 멘토 거절/수락 API
PATCH localhost:8080/admin/mentors/mentor-requests/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "isAccepted" : "REJECTED"
}

### 멘토 정산 내역 조회 API
GET localhost:8080/admin/mentors/settlements
Authorization: Bearer {{token}}

### 멘토 정산 내역 상세 조회 API
GET localhost:8080/admin/mentors/settlements/1
Authorization: Bearer {{token}}


