### 로그인 - 멘토
POST localhost:8080/login
Content-Type: application/json

{
  "email" : "asdf132345@naver.com",
  "password" : "asdf1234!@"
}

### 로그인 - 멘티
POST localhost:8080/login
Content-Type: application/json

{
  "email" : "abc@naver.com",
  "password" : "asdf1234!@"
}

> {%
  client.global.set("token",response.body.token);
  client.log("Token saved: " + client.global.get("token"));
%}

### 결제 내역 전체 조회
GET localhost:8080/payment-history
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

### 결제 내역 단건 조회 - 멘티
GET localhost:8080/payment-history/1/mentees
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

### 결제 내역 단건 조회 - 멘토 (멘티의 결제 내역이 조회됨)
GET localhost:8080/payment-history/1/mentors
Content-Type: application/json
Authorization: Bearer {{token}}
