### 게시글 생성
POST localhost:8080/posts/1/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title" : "자유 게시글 - 테스트",
  "content" : "테스트를 위한 게시글 생성입니다.",
  "postType" : "FREE"
}

> {%
  client.global.get("auth.token");
%}

### 게시글 목록 조회
GET localhost:8080/posts

### 게시글 목록 조회
GET localhost:8080/posts/2

### 댓글 수정
PATCH localhost:8080/posts/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title" : "게시글 제목 수정 테스트입니다.",
  "content" : "게시글 내용 수정 테스트입니다."
}

> {%
  client.global.get("auth.token");
%}

### 댓글 삭제
DELETE localhost:8080/posts/3
Authorization: Bearer {{token}}

> {%
  client.global.get("auth.token");
%}
