name: Deploy to AWS EC2

on:
  push:
    branches:
      - feature/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions 실행 환경

    steps:
      # ✅ 1️⃣ GitHub 저장소 코드 가져오기
      - name: Checkout Repository
        uses: actions/checkout@v2

      # ✅ 2️⃣ JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ 3️⃣ Gradle 빌드 (Spring Boot JAR 파일 생성)
      - name: Build JAR file
        run: |
          chmod +x gradlew
          ./gradlew build -x test  # 테스트 제외하고 빌드 실행

      # ✅ 4️⃣ Docker 로그인 (GitHub Secrets 사용)
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ✅ 5️⃣ Docker 이미지 빌드 & 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

      # ✅ 6️⃣ EC2에 SSH 접속 후 배포 (최신 Docker 이미지 실행)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d -p 8080:8080 --env-file .env --name backend-container ${{ secrets.DOCKER_USERNAME }}/my-backend:latest