name: Deploy to AWS EC2

on:
  push:
    branches:
      - refactor/deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR file
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/my-backend .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/codeness
            git pull origin refactor/deploy-test
            docker-compose pull
            docker-compose down
            docker-compose up -d
